<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Project1</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="SupportedOS.fs" />
    <Compile Include="SupportedOSAttribute.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.analyzers" Version="1.27.0" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
  </ItemGroup>

</Project>
